# For local development - REMOVE BEFORE COMMITTING TO GIT
OPENAI_API_KEY = "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"  # Get from platform.openai.com
DATABASE_URL = "sqlite:///survey.db"       # For production: "postgresql://user:pass@host/db"

